[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {namespaces = false}

[project]
name = "pozo"
description = "Hel visualizing well log data - Herramienta para visualizar registros de pozos"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"
dependencies = [
 "ood >=1.0.1a",
 ]

[project.optional-dependencies]
dev = ["pytest"]

