# .github/workflows/ci-cd.yml
on:
  push:
    branchs:
      - main
jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pozo
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout
      if: startsWith(github.ref, 'refs/tags')
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: python3 -m pip install --upgrade build && python3 -m build
      if: startsWith(github.ref, 'refs/tags')
    - name: Publish package distributions to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
